# Netlify config file
# https://docs.netlify.com/configure-builds/file-based-configuration/
[build]
  command = "npm run build"
  publish = "public"
[build.environment]
    # cache Cypress binary in local "node_modules" folder
    # so Netlify caches it
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    # set TERM variable for terminal output
    TERM = "xterm"

[[plugins]]
  package = "netlify-plugin-cypress"
  # optional: record the test results and videos to Cypress Dashboard
  # https://on.cypress.io/dashboard-introduction
  # note: we have set the CYPRESS_RECORD_KEY environment variable
  # using Netlify UI to keep it secret
  [plugins.inputs]
  record = true
  group = "netlify"
  tag = "..."
  spec = "cypress/integration/smoke*.js"
